### ISSUE TITLE
MEA-EDOMUS : optimiser token_strings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patdie421/mea-edomus#46]
```
token_strings est peu efficace (en perd). voir l'utilisation d'un dictionnaire.

```

Original issue reported on code.google.com by `patrice....@gmail.com` on 26 Jun 2013 at 9:13

**Comment by patdie421** [comment]
3 méthodes d'accès : séquentiel, par index trié et recherche dichotomique et hashage (sélection à la compilation)
