### ISSUE TITLE
MEA-EDOMUS : ajouter un automate (minimaliste)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patdie421/mea-edomus#50]
```
Un automate est nécessaire pour que la solution soit vraiment fonctionnelle.

Faire à minima dans un premier temps en attendant des spéc complètes


```

Original issue reported on code.google.com by `patrice....@gmail.com` on 2 Jul 2013 at 10:53

**Comment by patdie421** [comment]
Première version de l'automate disponible. Redéveloppement complet sur la base d'une structure json et d'un mini compilateur.

**Comment by patdie421** [comment]
fait
